- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: start mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: install boto3, botocore, and PyMySQL
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
    - boto3
    - botocore
    - PyMySQL

- name: fetch mysql root password from ssm
  ansible.builtin.set_fact:
    MYSQL_ROOT_PASSWORD: "{{ lookup('amazon.aws.aws_ssm', '/roboshop/dev/mysql/mysql_root_password', region='us-east-1', decrypt=True) }}"

- name: set MySQL root password
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ MYSQL_ROOT_PASSWORD }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
